DATABASE_HOST = "192.168.206.133"
DATABASE_PORT = 3306
DATABASE_USER = "fflock"
DATABASE_PASSWD = "fflock"
DATABASE_NAME = "fflock"

ENCODER = "ffmpeg"
NFS_PATH = ""
SLAVE_MOUNT_PREFIX_PATH = ""
S3ID = ""
S3KEY = ""
S3BUCKET = ""
CONFIG_FILE = ""

FETCH_RETRIES = 3
