DATABASE_HOST = ""
DATABASE_PORT = 3306
DATABASE_USER = "fflock"
DATABASE_PASSWD = "fflock"
DATABASE_NAME = "fflock"

ENCODER = "ffmbc"
SLAVE_MOUNT_PREFIX_PATH = ""
S3ID = "AKIAIU74ID2ND5BQ7IEQ"
S3KEY = "6uUCDnWcsxUes1CVxSw64HAa3r03IGXW2olpcdJR"
S3BUCKET = "fflock"
CONFIG_FILE = ""
